version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: php-app
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: survey_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
